name: template_syntax
description: Template Syntax
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.3.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+4
  angular_components: ^0.9.0-alpha+5
  angular_forms: ^1.0.1-alpha+2

dev_dependencies:
  angular_test: ^2.0.0-alpha
  build_runner: ^0.7.10+1
  build_test: ^0.10.0
  build_web_compilers: ^0.3.0
  # Temporarily use mock pageloader (https://github.com/dart-lang/site-webdev/issues/1277):
  pageloader:
    path: ../../../util/pageloader
  test: ^0.12.30
