name: ng_test.github_issues
description: Demo of angular_test
version: 0.0.1
environment:
  sdk: '>=2.0.0-dev.3.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+4
  angular_forms: ^1.0.1-alpha+2
  markdown: ^1.0.0
  ng_bootstrap: ^0.9.0
  sass_transformer: ^0.1.2+1

dev_dependencies:
  angular_test: ^2.0.0-alpha
  build_runner: ^0.7.10+1
  build_test: ^0.10.0
  build_web_compilers: ^0.3.0
  mockito: ^2.0.2
  pageloader: ^2.2.5
  test: ^0.12.30

# Until ng_bootstrap is updated
dependency_overrides:
  angular: 5.0.0-alpha+4
