# #docregion
name: angular_tour_of_heroes
description: Tour of Heroes
version: 0.0.1

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha

# #docregion dev_dependencies
dev_dependencies:
  angular_test: ^2.0.0-alpha+2
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.30
  build_runner:
  build_test:
  build_web_compilers:
# #enddocregion dev_dependencies

dependency_overrides:
  analyzer: 0.31.0+1
