name: api_docs
description: >
  Pubspec used to fetch specific versions of packages for the purpose of generating API docs,
  and for checking if new versions are available (see gulp/pkg-vers.js).
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.32.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+6
  angular_components: ^0.9.0-alpha+6
  angular_forms: ^1.0.1-alpha+6
  angular_router: ^2.0.0-alpha+6
  angular_test: ^2.0.0-alpha+4

dev_dependencies:
  build_runner: ^0.7.11+1
  build_test: ^0.10.1
  build_web_compilers: ^0.3.1

# dependency_overrides:
