# #docplaster
name: router_example
description: Router Example
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.3.0 <2.0.0'

# #docregion dependencies, dependencies-wo-forms
dependencies:
  angular: ^5.0.0-alpha+4
  # #enddocregion dependencies-wo-forms
  angular_forms: ^1.0.1-alpha+2
  # #docregion dependencies-wo-forms
  angular_router: ^2.0.0-alpha+2
# #enddocregion dependencies, dependencies-wo-forms

dev_dependencies:
  build_runner: ^0.7.10+1
  build_test: ^0.10.0
  build_web_compilers: ^0.3.0
